language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-26.1.0
    - platform-tools
    - android-26
    
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

notifications:
  email: false
  
script:
    - ./gradlew test
